### ISSUE TITLE
TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by bitboxx** [cloudcmd/console#4]
I have a problem trying to get console-io working on a freshly installed linux box running Node.js 7.5.0.

The server would listen to port 1337 just fine, but as soon as I open http://<ip address>:1337 it shows error messages on the console. In the front end, only a blank page is shown. Inspector show 500 error from http://<ip address>:1337/console/modules.json

Maybe Socket.io API has changed? The version installed is socket.io@1.7.2

```
root@arch-c1e2 / # npm i console-io -g
...

root@arch-c1e2 / # console
url: http://0.0.0.0:1337
TypeError: Cannot read property 'path' of undefined
    at Function.module.exports.getSocketPath (/usr/lib/node_modules/console-io/server/console.js:46:18)
    at modules.forEach (/usr/lib/node_modules/console-io/server/index.js:79:37)
    at Array.forEach (native)
    at _modulesFn (/usr/lib/node_modules/console-io/server/index.js:77:17)
    at currify (/usr/lib/node_modules/console-io/node_modules/currify/legacy/lib/currify.js:27:45)
    at again (/usr/lib/node_modules/console-io/node_modules/currify/legacy/lib/currify.js:30:24)
    at /usr/lib/node_modules/console-io/node_modules/currify/legacy/lib/currify.js:14:19
    at Layer.handle [as handle_request] (/usr/lib/node_modules/console-io/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/console-io/node_modules/express/lib/router/route.js:131:13)
    at _konsoleFn (/usr/lib/node_modules/console-io/server/index.js:116:5)
♥

root@arch-c1e2 / # node --version 
v7.5.0

```

**Comment by coderaiser** [comment]
Thank you, fixed with 435c2c6. Landed in [v3.0.9](https://github.com/cloudcmd/console/releases/tag/v3.0.9).
